:toc:

= Le modèle MVC par l'exemple

== Le principe du modèle MVC

Concevoir son application en respectant une séparation *M* odèle - *V* ue - *C* ontrôleur, comme défini ci-dessous :

[plantuml, "modele-mvc", png]  
----
@startuml

package modèle
package contrôleur
package vue

vue -> contrôleur
contrôleur -> modèle
modele <.. vue

@enduml
----

=== Le modèle

Cette partie contient l'ensemble des éléments liés au modèle de données *métier* de l'application.

On peut notamment y retrouver les classes correspondant aux tables d'une base de données.

Ces classes sont appelées les *entités*.

=== La vue

Cette partie contient l'ensemble des éléménts qui composent l'interface graphique (*IHM*) de l'application.

Cette IHM peut être :

* un *client léger* : interface web (utilisant les technologies HTML / JavaScript / CSS) exécutée depuis un navigateur (Chrome, Internet Explorer, Firefox...)
* un *client lourd* : interface exécutable directement depuis le système d'exploitation (Swing, QT, GTK...)
* pourquoi pas une simple sortie console

=== Le contrôleur

Cette partie contient l'ensemble des éléments qui permettent de contrôler les données qui transitent entre la vue et le modèle :

* *ce passage par le contrôleur est obligatoire dans le cas d'une écriture (création, modification, suppression) de données*
* ce passage par le contrôleur peut être facultatif dans le cas d'une lecture de données : dans ce cas, la vue peut directement (selon l'architecture logicielle) les obtenir depuis le modèle

*L'intérêt de l'utilisation de ce modèle ?*

* construire son application de manière organisée, en définissant les rôles de chaque composant
** un élément de la vue doit uniquement afficher et intéragir avec l'utilisateur
** un élément du contrôleur doit uniquement traiter (souvent vérifier) les données qui transitent vers le modèle
** un élément du modèle doit structurer et permettre le stockage des données
* faciliter la maintenance de son application
** plus l'organisation est respectée, plus un problème sera rapide à investiguer
* permettre la conception d'applications "multi-tiers" ou "multi-plateformes"

== Un cas concret : une application simple d'affichage des étudiants

Dans les exemples qui vont suivre, nous allons voir plusieurs solutions techniques qui pourraient être proposées - tout en respectant le modèle MVC - pour le développement d'une application (très simple) d'affichage des étudiants.

Cette application doit :

* stocker les informations sur un certain nombre d'étudiants (nom, prénom, année, groupe de TD, groupe de TP)
* présenter cette liste d'étudiants
** soit l'ensemble des étudiants
** soit les étudiants répondant à une recherche par critère
* permettre les trois actions suivantes :
** ajout d'un étudiant
** modification d'un étudiant
** suppression d'un étudiant

*Voici une proposition de maquette simple :*

[plantuml, "maquette", png]
----
@startsalt
{
    = Liste des étudiants
    | . 
    
    == Recherche
    | . 
    {
        Nom : | "Saisir un nom..." | . | . | . | Prénom : | "Saisir un prénom..." | . | . | . | Groupe de TP : | ^Sélectionner un Groupe de TP...^ | . | . | . | [Rechercher] | [Afficher tout]
    }
    
    | . 
    
    == Actions
    | . 
    {
        [Ajouter un étudiant] | . | . | . | ^Sélectionner un Groupe de TP...^ | [Modifier] | [Supprimer]
    }
    
    | . 
    
    {#
        <b>Nom | <b>Prénom | <b>Année | <b>Groupe de TD | <b>Groupe de TP
        ABALO | Luc | 2 | 1 | A
        BAILLE | Cyril | 2 | 2 | B
        BRYANT | Kobe | 1 | 1 | A
        CURRY | Stephen | 1 | 1 | B
        DESCHAMPS | Didier | 2 | 4 | B
        DUPONT | Antoine | 2 | 1 | B
    }
}
@endsalt
----

=== link:exemple1.html[Exemple 1 - Une application 100% Java]

=== link:exemple2.html[Exemple 2 - Une application Java / Web]

=== link:imaginer-plus-loin.html[Imaginer plus loin - Une solution multi-plateformes]