:toc:

= Le modèle MVC par l'exemple

== Le principe du modèle MVC

Concevoir son application en respectant une séparation *M* odèle - *V* ue - *C* ontrôleur, comme défini ci-dessous :

[plantuml, "modele-mvc", png]  
----
@startuml

package modele
package controleur
package vue

vue -> controleur
controleur -> modele
modele <.. vue

@enduml
----

=== Le modèle

Cette partie contient l'ensemble des éléments liés au modèle de données *métier* de l'application.

On peut notamment y retrouver les classes correspondant aux tables d'une base de données.

Ces classes sont appelées les *entités*.

=== La vue

Cette partie contient l'ensemble des éléménts qui composent l'interface graphique (*IHM*) de l'application.

Cette IHM peut être :

* un *client léger* : interface web (utilisant les technologies HTML / JavaScript / CSS) exécutée depuis un navigateur (Chrome, Internet Explorer, Firefox...)
* un *client lourd* : interface exécutable directement depuis le système d'exploitation (Swing, QT, GTK...)
* pourquoi pas une simple sortie console

=== Le contrôleur

Cette partie contient l'ensemble des éléments qui permettent de contrôler les données qui transitent entre la vue et le modèle :

* *ce passage par le contrôleur est obligatoire dans le cas d'une écriture (création, modification, suppression) de données*
* ce passage par le contrôleur peut être facultatif dans le cas d'une lecture de données : dans ce cas, la vue peut directement (selon l'architecture logicielle) les obtenir depuis le modèle

*L'intérêt de l'utilisation de ce modèle ?*

* construire son application de manière organisée
* faciliter sa maintenance
* permettre la conception d'applications "multi-tiers" (voir exemple 2)

== Un cas concret : une application simple d'affichage des étudiants

Dans les exemples qui vont suivre, nous allons voir plusieurs solutions techniques qui pourraient être proposées - tout en respectant le modèle MVC - pour le développement d'une application (très simple) d'affichage des étudiants.

Cette application doit :

* stocker les informations sur un certain nombre d'étudiants (nom, prénom, année, groupe de TD, groupe de TP)
* présenter cette liste d'étudiants
** soit l'ensemble des étudiants
** soit les étudiants répondant à une recherche par critère
* permettre les trois actions suivantes :
** ajout d'un étudiant
** modification d'un étudiant
** suppression d'un étudiant

=== Exemple 1 - Une application 100% Java

Dans cet exemple, nous allons détailler l'architecture d'une première solution, dont voici les spécificités techniques :

* stockage des informations sur les étudiants dans des fichiers CSV (texte utilisant un séparateur)
* interface graphique en *Swing*

La technologie *Java* est donc la seule utilisée.

==== La partie "modèle"

[NOTE]
====
Cette partie est valable pour tous les exemples.
====

Les classes du modèle sont dans le package `org.blagnac.coo.mvcexample.model` :

* `Etudiant.java`
* `GroupeTD.java`
* `GroupeTP.java`

[plantuml, "modele", png]  
----
@startuml

package org.blagnac.coo.mvcexample.model {
    class Etudiant {
        - identifiant: String
        - nom: String
        - prenom: String
        - groupeTP: GroupeTP
        + get...()
        + set...(...)
    }
    
    class GroupeTP {
        - identifiant: String
        - groupeTD: GroupeTD
        - groupe: Character
        + get...()
        + set...(...)
    }
    
    class GroupeTD {
        - identifiant: String
        - annee: int
        - numero: int
        + get...()
        + set...(...)
    }
}

Etudiant "1..*" -- "1" GroupeTP
GroupeTP "1..2" -- "1" GroupeTD

@enduml
----

Comme expliqué plus haut, ces classes peuvent être assimilées à des entités, c'est à dire la correspondance en classes Java de notre "pseudo" modèle de données.

===== Le stockage des informations

Si nous devions imaginer un modèle de base de données pour notre application, nous aurions pu proposer ceci :

Pour simplifier, nous utilisons donc les fichiers CSV suivants, en guise de stockage des informations :

* `src/main/resources/groupesTD.csv` : liste des groupes de TD (colonnes identifiant, année, numéro)
* `src/main/resources/groupesTP.csv` : liste des groupes de TP (colonnes identifiant, groupe de TD associé, groupe)
* `src/main/resources/etudiants.csv` : liste des étudiants (colonnes nom, prénom, groupe de TP associé)

Au lancement de l'application, les données sont chargées dans des variables statiques, accessibles dès lors depuis n'importe quelle classe. Ce processus a lieu dans `org.blagnac.coo.mvcexample.controller.MainController > loadData()`, et est appelé depuis la classe principale.

Nous allons donc ajouter aux classes du modèle des méthodes statiques de chargement (à partir de la lecture des fichiers CSV) et d'accès aux données (avec potentiellement du tri, du filtrage, etc...).

[NOTE]
====
Par bonne pratique, dans le cas de l'utilisation d'une vraie base de données, ces méthodes d'accès aux données (par requêtage SQL donc) seraient placées dans d'autres classes.
====

[plantuml, "stockage-infos", png]  
----
@startuml

folder "src/main/java" {
    package org.blagnac.coo.mvcexample.ex1 {
        class Exemple1Application {
            + {static} main(String[] args)
        }
    }
    
    package org.blagnac.coo.mvcexample.controller {
        class MainController {
            + {static} loadData()
        }
    }
    
    package org.blagnac.coo.mvcexample.model {
        class Etudiant {
            - identifiant: String
            - nom: String
            - prenom: String
            - groupeTP: GroupeTP
            - {static} LISTE: List<Etudiant>
            + get...()
            + set...(...)
            + {static} loadEtudiants()
            + {static} getAll()
            + {static} getBy(String nom, String prenom, String identifiantGroupeTP)
        }
        
        class GroupeTP {
            - identifiant: String
            - groupeTD: GroupeTD
            - groupe: Character
            - {static} LISTE: List<GroupeTP>
            + get...()
            + set...(...)
            + {static} loadGroupesTP()
        }
        
        class GroupeTD {
            - identifiant: String
            - annee: int
            - numero: int
            - {static} LISTE: List<GroupeTD>
            + get...()
            + set...(...)
            + {static} loadGroupesTD()
        }
    }
}

folder "src/main/resources/csv" {
    file etudiants.csv {
    }
    
    file groupesTP.csv {
    }
    
    file groupesTD.csv {
    }
}

Exemple1Application --> MainController: loadData()
MainController -> Etudiant: loadEtudiants()
MainController -> GroupeTP: loadGroupesTP()
MainController -> GroupeTD: loadGroupesTD()

Etudiant "1..*" -- "1" GroupeTP
GroupeTP "1..2" -- "1" GroupeTD
Etudiant --> etudiants.csv: Lecture du fichier CSV
GroupeTP --> groupesTP.csv: Lecture du fichier CSV
GroupeTD --> groupesTD.csv: Lecture du fichier CSV

@enduml
----

==== La partie "vue"

[plantuml, "ex1-vue", png]  
----
@startuml



@enduml
----

Les classes du modèle sont dans le package `org.blagnac.coo.mvcexample.ex1.view` :

* `Fenetre.java` : la classe qui permet l'affichage de la fenêtre principale de l'application
* `EnTete.java` : la classe qui permet l'affichage des filtres de recherche et des boutons
* `Tableau.java` : la classe qui permet l'affichage du tableau des étudiants

===== Intéractions avec le modèle et le contrôleur

A plusieurs endroits, des éléments de l'IHM ont besoin d'utiliser des données du modèle :

* en lecture :
** la liste déroulante pour filtrer par groupe de TP : `EnTete > getGroupesTP()`
** le tableau des étudiants : `Tableau > majTableau(...)`

*Dans ce cas, la vue peut accéder directement au modèle, ce qu'elle fait par l'utilisation de `Etudiant.getAll()`, `Etudiant.getBy(...)` et `GroupeTP.LISTE`*.

* en écriture :

*Dans ce cas, un contrôleur doit donc intervenir, pour faire transiter les données à ajouter / modifier / supprimer entre la vue (l'IHM) et le modèle (les données).*

==== La partie "contrôleur"

[plantuml, "ex1-controleur", png]  
----
@startuml



@enduml
----

Les classes du modèle sont dans le package `org.blagnac.coo.mvcexample.ex1.controller` :

* `Exemple1EtudiantController.java` : le contrôleur qui concerne les étudiants
** méthode `create()` : ajout d'un étudiant
** méthode `update()` : modification d'un étudiant
** méthode `delete()` : suppression d'un étudiant

==== Intégralité de l'application

=== Exemple 2 - Une application Java / Web

[NOTE]
====
Cet exemple contient du Java hors programme (l'utilisation du framework Spring-Boot...). Ne pas s'en soucier.
====

==== La partie "modèle"

==== La partie "vue"

==== La partie "contrôleur"

==== Intégralité de l'application

=== Imaginer plus loin - Une solution multi-plateformes

==== La partie "modèle"

==== La partie "vue"

==== La partie "contrôleur"